receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317

exporters:
  debug:
    verbosity: detailed

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"


service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp, zipkin]
    metrics:
      receivers: [otlp]
      exporters: [debug]
